const BondingTexts = {
  buypozData:[
    {
      id: 1,
      claim: true,
      imgurl: '/img/bonding/usdc-logo32.svg',
      name: 'USDC',
      subname: 'Circle',
      locked: true,
      pozPrice: '$8.05',
      discount: '12.52%',
      currentlylocked: '304 POZ',
      totalpurchase: '8428 USDC',
      duration: '14 days',
      nextPozclaim: '04:30:40 days',
      bondingend: '',
      maximum: '10 000 POZ',
      buyBtnname: 'Buy POZ with USDC',
    },
    {
      id: 2,
      claim: false,
      imgurl: '/img/bonding/reward-logo2.svg',
      name: 'BCT',
      subname: 'Toucan Protocol',
      locked: true,
      pozPrice: '17,8',
      discount: '12.52',
      currentlylocked: '304',
      totalpurchase: '8428',
      duration: 14,
      nextPozclaim: '',
      bondingend: '04:30:40',
      maximum: '10 000',
      buyBtnname: 'Buy POZ with BCT',
    },
    {
      id: 3,
      claim: false,
      imgurl: '/img/bonding/token-logo3.svg',
      name: 'SLR',
      subname: 'Solarcoin',
      locked: false,
      pozPrice: '8.05',
      discount: '12.52',
      currentlylocked: '',
      totalpurchase: '',
      duration: '14',
      nextPozclaim: '',
      maximum: '10 000',
      buyBtnname: 'Buy POZ with SLR',
    },
  ],

  rewardData:[
    {
      text: 'New reward',
      imgurl: '/img/bonding/reward-logo1.svg',
      text1: 'You currently have POZ rewards ready to be claimed.',
      text2: 'Next reward available in 04:43 hours',
      claim: true,
    },
    {
      text: 'New reward',
      imgurl: '/img/bonding/reward-logo2.svg',
      text1: 'You currently have POZ rewards ready to be claimed.',
      text2: 'Next reward available in 04:43 hours',
      claim: true,
    },
    {
      text: 'Next reward',
      imgurl: '/img/bonding/token-logo3.svg',
      text1: 'You next POZ reward will be available soon. Stay tunned!',
      text2: 'Available in 04:43 hours',
      claim: false,
    },
  ]
}

export default BondingTexts;